
const translations = {
    fr: {
        zah: "je suis",
        trad1: "Accueil",
        trad2: "À propos",
        trad3: "Compétences",
        trad4: "Éducation",
        trad5: "Projets",
        trad6: "Loisirs",
        trad7: "Contact",
        trad8: "English",
        trad9: "Français",
        trad10: "Español",
        trad11: "Télécharger CV",
        trad12: "Bienvenue sur notre site Web",
        trad13: "Je suis un étudiant en gestion spécialisé en analyse financière, gestion des ressources humaines et marketing. Je me concentre sur l'efficacité organisationnelle et l'innovation.",
        trad14: "Je suis motivé par l'amélioration continue et j'aspire à contribuer au développement durable des entreprises.",
        trad15: "Langues & Compétences",
        trad16: "Je suis un étudiant en gestion avec une solide formation en langues et compétences managériales.",
        trad17: "Langues",
        trad18: "Compétences",
        trad19: "Langues",
        trad20: "langue Maternelle",
        trad21: "Français",
        trad22: "Anglais",
        trad23: "Compétences",
        trad24: "Gestion de Projet",
        trad25: "Analyse Financière",
        trad26: "Comptabilité",
        trad27: "Marketing",
        trad28: "Mon Éducation",
        trad29: "Engagez-moi",
        trad30: "CEPE",
        trad31: "Lycée Chrétien Atsimoniavoko",
        trad32: "Obtention du CEPE en 2016, marquant la fin de mon éducation primaire.",
        trad33: "BEPC",
        trad34: "Lycée Chrétien Atsimoniavoko",
        trad35: "Obtention du BEPC en 2020, validant le cycle d'éducation secondaire.",
        trad36: "Baccalauréat",
        trad37: "Lycée André Resempa Antsirabe",
        trad38: "Obtention du Baccalauréat en 2023, ouvrant les portes à l'université.",
        trad39: "1ère Année en Management",
        trad40: "Université FJKM Ravelojaona Antsirabe",
        trad41: "Début de ma première année en management en 2023 à l'Université FJKM.",
        trad42: "Mes Projets",
        trad43: "Tous les Projets",
        trad44: "Ressources Humaines",
        trad45: "Leadership",
        trad46: "Analyse des pratiques de recrutement dans une entreprise locale et recommandations pour attirer des talents diversifiés",
        trad47: "Étude des stratégies de rétention des employés et proposition d'un plan pour réduire le turnover dans une PME.",
        trad48: "Mise en place d'un système d'évaluation des performances pour améliorer la satisfaction et la productivité des employés.",
        trad49: "Développement d'un programme de formation en leadership pour les cadres intermédiaires dans une organisation.",
        trad50: "Recherche sur l'impact des styles de leadership sur la culture d'entreprise et l'engagement des employés.",
        trad51: "Élaboration d'une stratégie de communication interne pour renforcer la transparence et la confiance au sein de l'équipe.",
        trad52: "Loisirs",
        trad53: "Image d'un joueur",
        trad54: "Image de randonnée",
        trad55: "Image d'un joueur de basketball",
        trad56: "Image d'un match de basketball",
        trad57: "Passionné de basketball, je trouve de la joie dans le jeu en équipe et les défis athlétiques.",
        trad58: "Basketball",
        trad59: "Image de randonnée",
        trad60: "Un randonneur passionné, j'apprécie la nature et les échappées en plein air pour me ressourcer.",
        trad61: "Randonnée",
        trad62: "Image de lecture",
        trad63: "Lecteur passionné, je trouve dans les livres une source infinie de connaissance et d'évasion.",
        trad64: "Lecture",
        trad65: "Image de lecture d'un livre",
        trad66: "Image d'une équipe",
        trad67: "Image de trekking",
        trad68: "Contact",
        trad69: "Dites Bonjour",
        trad70: "Icône TikTok",
        trad71: "Icône Facebook",
        trad72: "Icône Email",
        trad73: "Icône LinkedIn",
        trad74: "Pour toute question ou collaboration, n'hésitez pas à me contacter via le formulaire ci-dessous. Je suis étudiant en gestion et serais ravi de discuter de futures opportunités avec vous.",
        trad75: "Votre Nom",
        trad76: "Votre Nom",
        trad77: "Votre Email",
        trad78: "Votre Email",
        trad79: "Objet",
        trad80: "Objet",
        trad81: "Laissez un message ici",
        trad82: "Message",
        trad83: "Envoyer le Message",
        trad84: "Envoi en cours...",
        trad85: "Abonnez-vous à notre site",
        trad86: "Recevez les dernières nouvelles et mises à jour directement dans votre boîte de réception.",
        trad87: "Votre email",
        trad88: "Votre email",
        trad89: "S'abonner",
        trad90: "À propos",
        trad91: "Étudiant en gestion passionné par le développement personnel et professionnel,",
        trad92: "visant à contribuer efficacement aux projets tout en améliorant continuellement mes compétences.",
        trad93: "Qualité",
        trad94: "Sérieux",
        trad95: "Responsable",
        trad96: "Compétent",
        trad97: "Confiant",
        trad98: "Contact",
        trad99: "Lot IIi 74 Vatofotsy, Antsirabe",
        trad100: "fifalianarakotomalala711@gmail.com",
        trad101: "fifaliana.onrender.com",
        trad102: "Réseaux sociaux",
        trad103: "Facebook",
        trad104: "LinkedIn",
        trad105: "Instagram",
        trad106: "Fifaliana Rakotomalala",
    },
    en: {
        zah: "I'm",
        trad1: "Home",
        trad2: "About",
        trad3: "Skills",
        trad4: "Education",
        trad5: "Projects",
        trad6: "Leisure",
        trad7: "Contact",
        trad8: "English",
        trad9: "Français",
        trad10: "Español",
        trad11: "Download CV",
        trad12: "Welcome to Our Website",
        trad13: "I am a management student specializing in financial analysis, human resources management, and marketing. I focus on organizational efficiency and innovation.",
        trad14: "I am driven by continuous improvement and aspire to contribute to the sustainable development of businesses.",
        trad15: "Languages & Skills",
        trad16: "I am a management student with a solid foundation in languages and managerial skills.",
        trad17: "Languages",
        trad18: "Skills",
        trad19: "Languages",
        trad20: "native language",
        trad21: "French",
        trad22: "English",
        trad23: "Skills",
        trad24: "Project Management",
        trad25: "Financial Analysis",
        trad26: "Accounting",
        trad27: "Marketing",
        trad28: "My Education",
        trad29: "Hire Me",
        trad30: "CEPE",
        trad31: "Lycée Chrétien Atsimoniavoko",
        trad32: "Received the CEPE in 2016, marking the end of my primary education.",
        trad33: "BEPC",
        trad34: "Lycée Chrétien Atsimoniavoko",
        trad35: "Received the BEPC in 2020, validating the secondary education cycle.",
        trad36: "Baccalauréat",
        trad37: "Lycée André Resempa Antsirabe",
        trad38: "Received the Baccalauréat in 2023, opening the doors to university.",
        trad39: "1st Year in Management",
        trad40: "Université FJKM Ravelojaona Antsirabe",
        trad41: "Starting my first year in management in 2023 at FJKM University.",
        trad42: "My Projects",
        trad43: "All Projects",
        trad44: "Human Resources",
        trad45: "Leadership",
        trad46: "Analysis of recruitment practices in a local company and recommendations to attract diverse talents",
        trad47: "Study of employee retention strategies and proposal of a plan to reduce turnover in an SME.",
        trad48: "Implementation of a performance evaluation system to improve employee satisfaction and productivity.",
        trad49: "Development of a leadership training program for middle managers in an organization.",
        trad50: "Research on the impact of leadership styles on company culture and employee engagement.",
        trad51: "Development of an internal communication strategy to enhance transparency and trust within the team.",
        trad52: "Leisure",
        trad53: "Image of a player",
        trad54: "Image of hiking",
        trad55: "Image of a basketball player",
        trad56: "Image of a basketball game",
        trad57: "A basketball enthusiast, I find joy in team play and athletic challenges.",
        trad58: "Basketball",
        trad59: "Image of hiking",
        trad60: "An avid hiker, I appreciate nature and outdoor escapes to recharge.",
        trad61: "Hiking",
        trad62: "Image of reading",
        trad63: "A passionate reader, I find in books an endless source of knowledge and escape.",
        trad64: "Reading",
        trad65: "Image of reading a book",
        trad66: "Image of a team",
        trad67: "Image of trekking",
        trad68: "Contact",
        trad69: "Say Hello",
        trad70: "TikTok icon",
        trad71: "Facebook icon",
        trad72: "Email icon",
        trad73: "LinkedIn icon",
        trad74: "For any questions or collaborations, feel free to contact me through the form below. I am a management student and would be delighted to discuss future opportunities with you.",
        trad75: "Your Name",
        trad76: "Your Name",
        trad77: "Your Email",
        trad78: "Your Email",
        trad79: "Subject",
        trad80: "Subject",
        trad81: "Leave a message here",
        trad82: "Message",
        trad83: "Send Message",
        trad84: "Submitting...",
        trad85: "Subscribe to Our Website",
        trad86: "Receive the latest news and updates directly in your inbox.",
        trad87: "Your email",
        trad88: "Your email",
        trad89: "Subscribe",
        trad90: "About",
        trad91: "Management student passionate about personal and professional development,",
        trad92: "aiming to contribute effectively to projects while continually improving my skills.",
        trad93: "Quality",
        trad94: "Serious",
        trad95: "Responsible",
        trad96: "Skilled",
        trad97: "Confident",
        trad98: "Contact",
        trad99: "Lot IIi 74 Vatofotsy, Antsirabe",
        trad100: "fifalianarakotomalala711@gmail.com",
        trad101: "fifaliana.onrender.com",
        trad102: "Social Media",
        trad103: "Facebook",
        trad104: "LinkedIn",
        trad105: "Instagram",
        trad106: "Fifaliana Rakotomalala",
    },
    es: {
        zah: "Soy",
        trad1: "Inicio",
        trad2: "Acerca de",
        trad3: "Habilidades",
        trad4: "Educación",
        trad5: "Proyectos",
        trad6: "Ocio",
        trad7: "Contacto",
        trad8: "English",
        trad9: "Français",
        trad10: "Español",
        trad11: "Descargar CV",
        trad12: "Bienvenido a nuestro sitio web",
        trad13: "Soy un estudiante de gestión especializado en análisis financiero, gestión de recursos humanos y marketing. Me enfoco en la eficiencia organizacional y la innovación.",
        trad14: "Estoy motivado por la mejora continua y aspiro a contribuir al desarrollo sostenible de las empresas.",
        trad15: "Idiomas y Habilidades",
        trad16: "Soy un estudiante de gestión con una sólida formación en idiomas y habilidades de gestión.",
        trad17: "Idiomas",
        trad18: "Habilidades",
        trad19: "Idiomas",
        trad20: "idioma materno",
        trad21: "Francés",
        trad22: "Inglés",
        trad23: "Habilidades",
        trad24: "Gestión de Proyectos",
        trad25: "Análisis Financiero",
        trad26: "Contabilidad",
        trad27: "Marketing",
        trad28: "Mi Educación",
        trad29: "Contrátame",
        trad30: "CEPE",
        trad31: "Lycée Chrétien Atsimoniavoko",
        trad32: "Obtuve el CEPE en 2016, marcando el final de mi educación primaria.",
        trad33: "BEPC",
        trad34: "Lycée Chrétien Atsimoniavoko",
        trad35: "Obtuve el BEPC en 2020, validando el ciclo de educación secundaria.",
        trad36: "Baccalauréat",
        trad37: "Lycée André Resempa Antsirabe",
        trad38: "Obtuve el Baccalauréat en 2023, abriendo las puertas a la universidad.",
        trad39: "1er Año en Gestión",
        trad40: "Université FJKM Ravelojaona Antsirabe",
        trad41: "Comenzando mi primer año en gestión en 2023 en la Universidad FJKM.",
        trad42: "Mis Proyectos",
        trad43: "Todos los Proyectos",
        trad44: "Recursos Humanos",
        trad45: "Liderazgo",
        trad46: "Análisis de las prácticas de reclutamiento en una empresa local y recomendaciones para atraer talentos diversos",
        trad47: "Estudio de estrategias de retención de empleados y propuesta de un plan para reducir la rotación en una PYME.",
        trad48: "Implementación de un sistema de evaluación del desempeño para mejorar la satisfacción y productividad de los empleados.",
        trad49: "Desarrollo de un programa de formación en liderazgo para mandos intermedios en una organización.",
        trad50: "Investigación sobre el impacto de los estilos de liderazgo en la cultura empresarial y el compromiso de los empleados.",
        trad51: "Elaboración de una estrategia de comunicación interna para reforzar la transparencia y la confianza dentro del equipo.",
        trad52: "Ocio",
        trad53: "Imagen de un jugador",
        trad54: "Imagen de senderismo",
        trad55: "Imagen de un jugador de baloncesto",
        trad56: "Imagen de un juego de baloncesto",
        trad57: "Entusiasta del baloncesto, encuentro alegría en el juego en equipo y en los desafíos atléticos.",
        trad58: "Baloncesto",
        trad59: "Imagen de senderismo",
        trad60: "Un senderista ávido, aprecio la naturaleza y las escapadas al aire libre para recargar energías.",
        trad61: "Senderismo",
        trad62: "Imagen de lectura",
        trad63: "Un lector apasionado, encuentro en los libros una fuente inagotable de conocimiento y escape.",
        trad64: "Lectura",
        trad65: "Imagen de lectura de un libro",
        trad66: "Imagen de un equipo",
        trad67: "Imagen de trekking",
        trad68: "Contacto",
        trad69: "Di Hola",
        trad70: "Ícono de TikTok",
        trad71: "Ícono de Facebook",
        trad72: "Ícono de Correo Electrónico",
        trad73: "Ícono de LinkedIn",
        trad74: "Para cualquier pregunta o colaboración, no dudes en contactarme a través del formulario a continuación. Soy estudiante de gestión y estaría encantado de discutir oportunidades futuras contigo.",
        trad75: "Tu Nombre",
        trad76: "Tu Nombre",
        trad77: "Tu Correo Electrónico",
        trad78: "Tu Correo Electrónico",
        trad79: "Asunto",
        trad80: "Asunto",
        trad81: "Deja un mensaje aquí",
        trad82: "Mensaje",
        trad83: "Enviar Mensaje",
        trad84: "Enviando...",
        trad85: "Suscríbete a Nuestro Sitio Web",
        trad86: "Recibe las últimas noticias y actualizaciones directamente en tu bandeja de entrada.",
        trad87: "Tu correo electrónico",
        trad88: "Tu correo electrónico",
        trad89: "Suscribirse",
        trad90: "Sobre",
        trad91: "Estudiante de gestión apasionado por el desarrollo personal y profesional,",
        trad92: "con el objetivo de contribuir eficazmente a los proyectos mientras mejoro continuamente mis habilidades.",
        trad93: "Calidad",
        trad94: "Serio",
        trad95: "Responsable",
        trad96: "Hábil",
        trad97: "Confiado",
        trad98: "Contacto",
        trad99: "Lot IIi 74 Vatofotsy, Antsirabe",
        trad100: "fifalianarakotomalala711@gmail.com",
        trad101: "fifaliana.onrender.com",
        trad102: "Redes Sociales",
        trad103: "Facebook",
        trad104: "LinkedIn",
        trad105: "Instagram",
        trad106: "Fifaliana Rakotomalala",
    }
};

document.querySelectorAll('.lang-btn').forEach(button => {
    button.addEventListener('click', () => {
        const lang = button.getAttribute('data-lang');
        applyTranslations(lang);
    });
});

function applyTranslations(lang) {
    document.querySelectorAll('[data-key]').forEach(element => {
        const key = element.getAttribute('data-key');
        element.textContent = translations[lang][key];
    });
}

document.querySelector('.selected-language').addEventListener('click', function () {
    document.querySelector('.language-select').classList.toggle('open');
});

document.querySelectorAll('.language-options li').forEach(option => {
    option.addEventListener('click', function () {
        const selectedLanguage = document.querySelector('.selected-language');
        const flagSrc = this.querySelector('.flag').src;
        const languageName = this.querySelector('span').textContent;

        selectedLanguage.querySelector('.flag').src = flagSrc;
        selectedLanguage.querySelector('span').textContent = languageName;

        // Changer la langue de la page
        const lang = this.getAttribute('data-lang');
        applyTranslations(lang);
    });
});
